# Generated by Django 5.2.17 on 2026-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(),
        ),
    ]
