# Generated by Django 5.2.17 on 2026-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.TextField(blank=True, default=''),
        ),
    ]
